name: Deploy

on:
  push:
    branches: [ master ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Copy file to the remote location.
    - name: Deploy to Server
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.SSHKEY }}
        ARGS: "-e -c -r --delete"
        SERVER_PORT: ${{ secrets.PORT }}
        FOLDER: "./"
        SERVER_IP:  ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        SERVER_DESTINATION: "/var/www/html/test1"